---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front13
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: azure-vote-front13
    spec:
      containers:
        - name: azure-vote-front13
          image: externalizatn.azurecr.io/application:v1
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 20m
          env:
            - name: REDIS
              value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front13
spec:
  type: LoadBalancer
  ports:
    - port: 8000
  selector:
    app: azure-vote-front13