apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: azure-vote-front16
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: azure-vote-front16.{{ .Values.dnsName }}
      http:
        paths:
          - path: /
            backend:
              serviceName: azure-vote-front16
              servicePort: 8000