apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: azure-vote-front16
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: azure-vote-front16.7fa76087251e41cc9034.centralus.aksapp.io
      http:
        paths:
          - path: /
            backend:
              serviceName: azure-vote-front16
              servicePort: 8000