apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front16
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 8000
  selector:
    app: azure-vote-front16

