apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 8001
      targetPort: 8001
  selector:
    app: azure-vote-back

