apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-front
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
      labels:
        app: azure-vote-front
    spec:
      containers:
        - name: azure-vote-front
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
            - containerPort: 8001
          resources:
            requests:
              cpu: 10m
            limits:
              cpu: 20m
          env:
            - name: REDIS
              value: "azure-vote-back"
