---
server:
  maxThreads: 17
  applicationConnectors:
    - type: http
      port: 8000
      useForwardedHeaders: false
      acceptorThreads: 3
      selectorThreads: 6
  adminConnectors:
    - type: http
      port: 8001
      acceptorThreads: 1
      selectorThreads: 1
